import  image1  from './map-icon/1.png';
import  image2  from './map-icon/2.png';
import  image3  from './map-icon/3.png';
import  image4  from './map-icon/4.png';
import  image5  from './map-icon/5.png';
import  image6  from './map-icon/6.png';
import  image7  from './map-icon/7.png';
import  image8  from './map-icon/8.png';
import  image9  from './map-icon/9.png';
import  image10  from './map-icon/10.png';
import  image11  from './map-icon/11.png';
import  image12  from './map-icon/12.png';
import  image13  from './map-icon/13.png';
import  image14  from './map-icon/14.png';
import  image15  from './map-icon/15.png';
import  image16  from './map-icon/16.png';
import  image17  from './map-icon/17.png';
import  image18  from './map-icon/18.png';
import  image19  from './map-icon/19.png';
import  image20  from './map-icon/20.png';
import  image21  from './map-icon/21.png';
import  image22  from './map-icon/22.png';
import  image23  from './map-icon/23.png';
import  image24  from './map-icon/24.png';
import marker from './map-icon/marker.png';

export { image1, image2, image3, image4, image5, image6, image7, image8, image9, image10, image11, image12, image13, image14, image15, image16, image17, image18, image19, image20, image21, image22, image23, image24, marker};
