const COLORS = [
  { COLOR: '#FFFCB5' },
  { COLOR: '#FFEAB6' },
  { COLOR: '#FFD9C8' },
  { COLOR: '#FFDDE5' },
  { COLOR: '#FFD4FF' },
  { COLOR: '#DAD7FF' },
  { COLOR: '#DDFFE6' },
  { COLOR: '#DEF7C4' },
  { COLOR: '#D8FAFF' },
  { COLOR: '#D7E8FF' },
  { COLOR: '#B7CEF9' },
  { COLOR: '#E9E9E9' },
  { COLOR: '#FBD44A' },
  { COLOR: '#EAA775' },
  { COLOR: '#F4667C' },
  { COLOR: '#DC82D2' },
  { COLOR: '#9860E5' },
  { COLOR: '#9F8CF1' },
  { COLOR: '#59CB74' },
  { COLOR: '#ADDF84' },
  { COLOR: '#89D2EA' },
  { COLOR: '#4ECCCB' },
  { COLOR: '#46A1FD' },
  { COLOR: '#C2C2C2' },
];

export default COLORS;
